name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4

      - name: Lint code
        run: npm lint

      - name: Typecheck code
        run: npm typecheck

      - name: Test code
        run: npm test
