name: Code quality

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm test
